--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Homebrew)
-- Dumped by pg_dump version 14.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: account_id_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.account_id_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_id_sequence OWNER TO postgres;

--
-- Name: account_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.account_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.account_sequence OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    account_holder_name character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(255) NOT NULL,
    initial_balance numeric(38,2) NOT NULL,
    is_active boolean NOT NULL,
    phone_number character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_id_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_id_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_id_sequence OWNER TO postgres;

--
-- Name: transaction_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_sequence OWNER TO postgres;

--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    accountid bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    receiver_email character varying(255) NOT NULL,
    remarks character varying(255),
    sender_email character varying(255) NOT NULL,
    status character varying(255),
    transaction_id uuid NOT NULL,
    transaction_time timestamp(6) without time zone NOT NULL,
    transaction_type character varying(255) NOT NULL,
    "updated balance" numeric(38,2) NOT NULL,
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'TRANSFER'::character varying, 'PAYMENT'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, account_holder_name, account_type, created_at, date_of_birth, email, initial_balance, is_active, phone_number, updated_at) FROM stdin;
2	John Doe1	SAVINGS	2025-03-06 19:21:48.60171	1996-05-15	john1.doe@email.com	900.00	t	9816543210	2025-03-06 19:22:36.986551
1	John Doe	SAVINGS	2025-03-06 19:02:59.50979	1995-05-15	john.doe@email.com	1100.00	t	9876543210	2025-03-06 19:22:36.988716
3	John Doe2	SAVINGS	2025-03-07 10:24:18.679911	1996-05-15	john2.doe@email.com	1000.00	t	9816543210	2025-03-07 10:24:18.679911
4	John Doe4	SAVINGS	2025-03-07 10:26:58.772933	1996-05-15	john4.doe@email.com	1000.00	t	9816543210	2025-03-07 10:26:58.772933
5	John Doe4	SAVINGS	2025-03-09 13:59:12.430793	1996-05-15	johnghgrsfd2.doe@email.com	1000.00	t	9816543210	2025-03-09 13:59:12.430793
6	rfs	SAVINGS	2025-03-09 14:09:11.498794	2002-06-12	d@gmail.com	110.00	t	4377998778	2025-03-09 14:09:11.498794
10	rfs	SAVINGS	2025-03-09 17:38:57.77564	1999-07-14	d11@gmail.com	21209.00	t	4377998778	2025-03-09 17:44:43.958505
7	fuyew	CURRENT	2025-03-09 15:07:09.886589	2003-11-05	d1@gmail.com	165.00	t	4377998778	2025-03-09 17:44:43.959428
11	John Doe4	SAVINGS	2025-03-09 18:40:56.995842	1996-05-15	johnghgrsfddfs2.doe@email.com	1000.00	t	9816543210	2025-03-09 18:40:56.995842
12	John Doe4	SAVINGS	2025-03-09 18:41:05.755576	1996-05-15	john9.doe@email.com	1000.00	t	9816543210	2025-03-09 18:41:05.755576
13	John Doe4	SAVINGS	2025-03-09 18:41:13.123806	1996-05-15	john10.doe@email.com	1000.00	t	9816543210	2025-03-09 18:41:13.123806
14	Riya Shreyas Desai	SAVINGS	2025-03-10 10:18:25.12685	1999-01-01	rs4desai@uwaterloo.ca	2000.00	t	4379706667	2025-03-10 10:18:25.12685
15	John Doe4	SAVINGS	2025-03-10 10:40:11.725099	1996-05-15	john11.doe@email.com	100.00	t	4379706667	2025-03-10 10:40:11.725099
16	Riya Shreyas Desai	SAVINGS	2025-03-10 10:54:19.040619	1999-01-01	rs6desai@uwaterloo.ca	100.00	t	4379706667	2025-03-10 10:54:19.040619
8	Riya Shreyas Desai	SAVINGS	2025-03-09 15:43:22.44704	1993-02-02	rs2desai@uwaterloo.ca	12146.00	t	4379706667	2025-03-10 12:34:31.419559
9	Riya Shreyas Desai	SAVINGS	2025-03-09 17:33:26.970482	1995-05-22	rs3desai@uwaterloo.ca	1187.00	t	4379706667	2025-03-10 12:34:31.425135
17	Riya Desai	SAVINGS	2025-03-10 16:14:51.019781	1996-05-15	riya1@email.com	1000.00	t	4379706667	2025-03-10 16:14:51.019781
18	Riya Shreyas Desai	SAVINGS	2025-03-10 16:23:36.695189	2000-01-01	rs7desai@uwaterloo.ca	1000.00	t	4379706667	2025-03-10 16:23:36.695189
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, accountid, amount, receiver_email, remarks, sender_email, status, transaction_id, transaction_time, transaction_type, "updated balance") FROM stdin;
1	2	100.00	john.doe@email.com	Transfer to john.doe@email.com	john1.doe@email.com	SUCCESS	0aa7ff95-3342-465b-9565-40694a602d60	2025-03-06 19:22:36.969049	WITHDRAWAL	900.00
2	1	100.00	john1.doe@email.com	Received from john1.doe@email.com	john.doe@email.com	SUCCESS	0aa7ff95-3342-465b-9565-40694a602d60	2025-03-06 19:22:36.983655	DEPOSIT	1100.00
3	10	123.00	d1@gmail.com	Transfer to d1@gmail.com	d11@gmail.com	SUCCESS	4e4b3e2f-67ca-4934-9e75-7234c838fd2f	2025-03-09 17:44:43.944518	WITHDRAWAL	21209.00
4	7	123.00	d11@gmail.com	Received from d11@gmail.com	d1@gmail.com	SUCCESS	4e4b3e2f-67ca-4934-9e75-7234c838fd2f	2025-03-09 17:44:43.956836	DEPOSIT	165.00
5	8	77.00	rs3desai@uwaterloo.ca	Transfer to rs3desai@uwaterloo.ca	rs2desai@uwaterloo.ca	SUCCESS	62f44e2d-a419-41a8-9321-785459a7ec2d	2025-03-09 23:04:55.193396	WITHDRAWAL	12256.00
6	9	77.00	rs2desai@uwaterloo.ca	Received from rs2desai@uwaterloo.ca	rs3desai@uwaterloo.ca	SUCCESS	62f44e2d-a419-41a8-9321-785459a7ec2d	2025-03-09 23:04:55.212033	DEPOSIT	1077.00
7	8	10.00	rs3desai@uwaterloo.ca	Transfer to rs3desai@uwaterloo.ca	rs2desai@uwaterloo.ca	SUCCESS	8f15c6ca-6bc2-4569-bb35-22a769013640	2025-03-10 09:07:24.690336	WITHDRAWAL	12246.00
8	9	10.00	rs2desai@uwaterloo.ca	Received from rs2desai@uwaterloo.ca	rs3desai@uwaterloo.ca	SUCCESS	8f15c6ca-6bc2-4569-bb35-22a769013640	2025-03-10 09:07:24.698621	DEPOSIT	1087.00
9	8	100.00	rs3desai@uwaterloo.ca	Transfer to rs3desai@uwaterloo.ca	rs2desai@uwaterloo.ca	SUCCESS	85420d19-8e17-4484-8211-af79265c0686	2025-03-10 12:34:31.401815	WITHDRAWAL	12146.00
10	9	100.00	rs2desai@uwaterloo.ca	Received from rs2desai@uwaterloo.ca	rs3desai@uwaterloo.ca	SUCCESS	85420d19-8e17-4484-8211-af79265c0686	2025-03-10 12:34:31.417017	DEPOSIT	1187.00
\.


--
-- Name: account_id_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_sequence', 1, false);


--
-- Name: account_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_sequence', 5, true);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 18, true);


--
-- Name: transaction_id_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_id_sequence', 10, true);


--
-- Name: transaction_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_sequence', 2, true);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: accounts ukn7ihswpy07ci568w34q0oi8he; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukn7ihswpy07ci568w34q0oi8he UNIQUE (email);


--
-- PostgreSQL database dump complete
--

