version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: banking-db
    environment:
      POSTGRES_DB: bankpoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: connect
    ports:
      - "5432:5432"

  banking-app:
    build: .
    container_name: banking-app
    ports:
      - "9902:9902"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
